# Generated by Django 5.1.2 on 2024-12-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApi', '0006_alter_team_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingApi.reservation'),
        ),
    ]
