# Generated by Django 5.1.2 on 2024-12-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApi', '0007_post_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
